package main;


import dataAnalyze.AddNewUserToProperties;
import dataAnalyze.UserPropertiesFileParsing;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zhuangjinghao
 */
public class AddDeleteUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddDeleteUser.class.getName());
    
    public static ArrayList<User> UserList;
    
        static {
        try {
            UserList = (ArrayList<User>) UserPropertiesFileParsing.loadUsers();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
    /**
     * Creates new form AddDeleteUser
     */
    public AddDeleteUser() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        for(User u : UserList){
            model.addRow(new Object[]{u.getUserID(), u.getUserName(), u.getPassword(), u.getRole()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        UserNameTextBox = new javax.swing.JTextField();
        PasswordTextBox = new javax.swing.JTextField();
        AddUserButton = new javax.swing.JButton();
        RemoveUserButton = new javax.swing.JButton();
        AdminOrNot = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        helpMenuBar = new javax.swing.JMenu();
        returnMenuBar = new javax.swing.JMenu();
        returnMainMenuBar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Resource Plan Beta 1.1");
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "UserName", "Password", "Position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UserTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(UserTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 0, -1, 576));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create a new User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, 30));

        UserNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextBoxActionPerformed(evt);
            }
        });
        getContentPane().add(UserNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, -1));
        getContentPane().add(PasswordTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, -1));

        AddUserButton.setText("Add");
        AddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        RemoveUserButton.setText("Remove");
        RemoveUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 120, -1));

        AdminOrNot.setText("It is an Admin");
        getContentPane().add(AdminOrNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel2.setText("username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 70, 20));

        jLabel3.setText("password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, -1));

        helpMenuBar.setText("Help");
        helpMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenuBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(helpMenuBar);

        returnMenuBar.setText("Return");

        returnMainMenuBar.setText("To Main Menu");
        returnMainMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMainMenuBarActionPerformed(evt);
            }
        });
        returnMenuBar.add(returnMainMenuBar);

        jMenuBar1.add(returnMenuBar);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnMainMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMainMenuBarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MainMenuUI().setVisible(true);
    }//GEN-LAST:event_returnMainMenuBarActionPerformed

    private void UserNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextBoxActionPerformed

    private void AddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        String Username = UserNameTextBox.getText();
        String Password = PasswordTextBox.getText();
        
        if(Username.isEmpty() || Password.isEmpty()){
            JOptionPane.showMessageDialog(this, "You can't have empty Username or Password!");
            return;
        }
        
        Short id = 0;
        String Position;
        
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 0);
            Object user = model.getValueAt(i, 1);
            if (value == null) continue;
            
            short existingId = (short) model.getValueAt(i, 0); // 第0列是ID
            if(user.equals(Username)){
                JOptionPane.showMessageDialog(this, "Username already exist!");
                return;
            }
            
            if (existingId == id) {
                id = (short)(id+1);
            }else{
                break;
            }
        }
        
        if(AdminOrNot.isSelected()){
            Position = "ADMIN";
        }else{
            Position = "EMPLOYEE";
        }
        
        model.addRow(new Object[]{id, Username, Password, Position});
        UserList.add(new User(id, Password, Username, Position));
        
        String PropertiesID = String.valueOf(id);
        try {
            AddNewUserToProperties.addUser(PropertiesID, Username, Password, Position);
        } catch (IOException ex) {}
    }//GEN-LAST:event_AddUserButtonActionPerformed

    private void RemoveUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveUserButtonActionPerformed
        // TODO add your handling code here:
        if(LoginUI.userIsAdmin){
            int selectedRow = UserTable.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Please select a product to delete!");
                return;
            }
        
            String targetId = UserTable.getValueAt(selectedRow, 0).toString();
        
            UserList.removeIf(u -> u.getUserID() == Short.parseShort(targetId));
        
            Properties prop = new Properties();
            try (FileInputStream in = new FileInputStream("data/users.properties")) {
                prop.load(in);
            } catch (IOException e) {
            }
        
            //user0.password
            int index = 0;
            while (prop.containsKey("user" + index + ".userID")) {
                if (prop.getProperty("user" + index + ".userID").equals(targetId)) {
                    prop.remove("user" + index + ".userID");
                    prop.remove("user" + index + ".userName");
                    prop.remove("user" + index + ".role");
                    prop.remove("user" + index + ".password");
                    break;
                }
                index++;
            }
        
            try {
                FileOutputStream out = new FileOutputStream("data/users.properties");
                prop.store(out, "Rebuilt User Data by: " + LoginUI.currentUser);
            } catch (IOException ex) {}
        
            DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "User deleted successfully!");
        }else{
            JOptionPane.showMessageDialog(this, "You have NO permission to delete User!");
        }  
    }//GEN-LAST:event_RemoveUserButtonActionPerformed

    private void helpMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenuBarMouseClicked
        // TODO add your handling code here:
        // GPT's method to make the link clickable
        String url = "https://github.com/San1tater1122/ICS4U_Easy-Resources-Plan";

        JLabel link = new JLabel("<html>Go to our Github to see the tutorial! :)<br>"
                + "<a href=''>" + url + "</a></html>");

        link.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new java.net.URI(url));
                } catch (Exception ex) {}
            }
        });

        JOptionPane.showMessageDialog(null, link, "Tutorial", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_helpMenuBarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddDeleteUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserButton;
    private javax.swing.JCheckBox AdminOrNot;
    private javax.swing.JTextField PasswordTextBox;
    private javax.swing.JButton RemoveUserButton;
    private javax.swing.JTextField UserNameTextBox;
    private javax.swing.JTable UserTable;
    private javax.swing.JMenu helpMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem returnMainMenuBar;
    private javax.swing.JMenu returnMenuBar;
    // End of variables declaration//GEN-END:variables
}
