/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.InputTest;
import dataAnalyze.ProductPropertiesFileParsing;
import java.util.ArrayList;
import model.Product;
import dataAnalyze.AddNewProductToProperties;
import java.awt.Desktop;
import java.io.IOException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author zhuangjinghao
 */
public class AddProductInformation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddProductInformation.class.getName());
    
    public static ArrayList<Product> ProductData;
    
    static {
        try {
            ProductData = (ArrayList<Product>) ProductPropertiesFileParsing.loadProducts();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
    /**
     * Creates new form addProductInformation
     */
    public AddProductInformation() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        for(Product p : ProductData){
            model.addRow(new Object[]{p.getID(), p.getProductName(), p.getProductPrice(), p.getProductCategory(), p.getProductSupplier()});
        }
        //model.addRow(new Object[]{id, name, price, category, supplier});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        IDTextField = new javax.swing.JTextField();
        ProductNameTextField = new javax.swing.JTextField();
        ProductPrice = new javax.swing.JTextField();
        ProductCategory = new javax.swing.JTextField();
        ProductSupplier = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        IDLabel1 = new javax.swing.JLabel();
        IDLabel2 = new javax.swing.JLabel();
        IDLabel3 = new javax.swing.JLabel();
        IDLabel4 = new javax.swing.JLabel();
        AddProductButton = new javax.swing.JButton();
        SortButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        helpMenuBar = new javax.swing.JMenu();
        returnMenuBar = new javax.swing.JMenu();
        returnToMainMenuBar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Resource Plan Alpha 1.2");
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Price ($)", "Category", "Supplier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ProductTable);
        if (ProductTable.getColumnModel().getColumnCount() > 0) {
            ProductTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            ProductTable.getColumnModel().getColumn(1).setPreferredWidth(160);
            ProductTable.getColumnModel().getColumn(2).setPreferredWidth(15);
            ProductTable.getColumnModel().getColumn(3).setPreferredWidth(20);
            ProductTable.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 580));

        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 150, -1));
        getContentPane().add(ProductNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, -1));

        ProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductPriceActionPerformed(evt);
            }
        });
        getContentPane().add(ProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, -1));
        getContentPane().add(ProductCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 150, -1));
        getContentPane().add(ProductSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 150, -1));

        IDLabel.setText("Product Supplier");
        getContentPane().add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 140, 20));

        IDLabel1.setText("ID");
        getContentPane().add(IDLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, -1));

        IDLabel2.setText("Product Name");
        getContentPane().add(IDLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 140, 20));

        IDLabel3.setText("Product Price (CAD $)");
        getContentPane().add(IDLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 20));

        IDLabel4.setText("Product Category");
        getContentPane().add(IDLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, 20));

        AddProductButton.setText("Add Product");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        SortButton.setText("Sort Functon");
        SortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SortButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, -1));

        helpMenuBar.setText("Help");
        helpMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenuBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(helpMenuBar);

        returnMenuBar.setText("Return");

        returnToMainMenuBar.setText("To Main Menu");
        returnToMainMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMainMenuBarActionPerformed(evt);
            }
        });
        returnMenuBar.add(returnToMainMenuBar);

        jMenuBar1.add(returnMenuBar);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnToMainMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMainMenuBarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MainMenuUI().setVisible(true);
    }//GEN-LAST:event_returnToMainMenuBarActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    private void ProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductPriceActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        
        boolean a = true;
        boolean b = true;
        
        // 从输入框读取内容
        int id = -1;
        if(InputTest.integerInputTest(IDTextField.getText())){
            id = Integer.parseInt(IDTextField.getText());
        }else{
            a = false;
        }
        
        String name = ProductNameTextField.getText();
        
        float price = -1;
        if(InputTest.floatInputTest(ProductPrice.getText())){
            price = Float.parseFloat(ProductPrice.getText());
        }else{
            a = false;
        }
        
        String category = ProductCategory.getText();
        String supplier = ProductSupplier.getText();
        
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 0);
            if (value == null) continue;
            
            int existingId = (int) model.getValueAt(i, 0); // 第0列是ID
            
            if (existingId == id) {
                b = false; // 找到重复ID
                break;
            }
        }

        
        // 添加新行
        if(a && b){
            model.addRow(new Object[]{id, name, price, category, supplier});
            String strprice = String.valueOf(price);
            String strid = String.valueOf(id);
            try{
                AddNewProductToProperties.addproduct(strid, name, strprice, category, supplier);
            }catch(IOException e){
            }
            ProductData.add(new Product(id, name, price, category, supplier));
        }else{
            if(b){
                JOptionPane.showMessageDialog(null, "Information error, fail to add!");
            }else{
                JOptionPane.showMessageDialog(null, "Repeated Information, ID!");
            }
            
        }
        
    }//GEN-LAST:event_AddProductButtonActionPerformed
    
    private boolean idSortAscending = true;
    private void SortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortButtonActionPerformed
        // TODO add your handling code here:
        // 获取表格模型
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();

        // 创建或获取 TableRowSorter
        TableRowSorter<DefaultTableModel> sorter = (TableRowSorter<DefaultTableModel>) ProductTable.getRowSorter();
        if (sorter == null) {
            sorter = new TableRowSorter<>(model);
            ProductTable.setRowSorter(sorter);
        }

        // 设置排序键
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        
        if (idSortAscending) {
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING)); // ID 列升序
        } else {
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING)); // ID 列降序
        }
        sorter.setSortKeys(sortKeys);
        sorter.sort();

        // 切换排序状态，下次点击相反
        idSortAscending = !idSortAscending;
    }//GEN-LAST:event_SortButtonActionPerformed

    private void helpMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenuBarMouseClicked
        // TODO add your handling code here:
        // GPT's method to make the link clickable
        String url = "https://github.com/San1tater1122/ICS4U_Easy-Resources-Plan";

        JLabel link = new JLabel("<html>Go to our Github to see the tutorial! :)<br>"
                + "<a href=''>" + url + "</a></html>");

        link.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new java.net.URI(url));
                } catch (Exception ex) {}
            }
        });

        JOptionPane.showMessageDialog(null, link, "Tutorial", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_helpMenuBarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddProductInformation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductButton;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel IDLabel1;
    private javax.swing.JLabel IDLabel2;
    private javax.swing.JLabel IDLabel3;
    private javax.swing.JLabel IDLabel4;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField ProductCategory;
    private javax.swing.JTextField ProductNameTextField;
    private javax.swing.JTextField ProductPrice;
    private javax.swing.JTextField ProductSupplier;
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton SortButton;
    private javax.swing.JMenu helpMenuBar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu returnMenuBar;
    private javax.swing.JMenuItem returnToMainMenuBar;
    // End of variables declaration//GEN-END:variables
}
