/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import javax.swing.JOptionPane;

import model.User;
import dataAnalyze.UserPropertiesFileParsing;

import java.io.IOException;
import java.util.List;

import javax.swing.ImageIcon;   // ImageIcon
import java.awt.Image;           // Image


/**
 *
 * @author San1tater
 */
public class LoginUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginUI.class.getName());
    
    public static String currentUser = "noOne";
    public static boolean userIsAdmin = false;
    /**
     * Creates new form UI
     */
    public LoginUI() {
        initComponents();
        
        // GPT给的让Icon缩小的方法
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/IconImage/Icon.png"));
        Image scaledImage = originalIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ApplicationIcon.setIcon(new ImageIcon(scaledImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleButton = new javax.swing.JLabel();
        UsernameText = new javax.swing.JLabel();
        PasswordText = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ApplicationIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Resource Plan Alpha 1.2");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleButton.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        TitleButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleButton.setText("Welcome to Easy Resource Plan!");
        TitleButton.setName(""); // NOI18N
        getContentPane().add(TitleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 800, -1));

        UsernameText.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        UsernameText.setText("Username:");
        getContentPane().add(UsernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 179, -1, 32));

        PasswordText.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        PasswordText.setText("Password:");
        getContentPane().add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 246, 88, 37));
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 179, 347, 32));

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 248, 347, 37));

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 334, -1, -1));

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 334, -1, -1));

        ApplicationIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ApplicationIcon.setMaximumSize(new java.awt.Dimension(100, 100));
        ApplicationIcon.setMinimumSize(new java.awt.Dimension(100, 100));
        ApplicationIcon.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(ApplicationIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 180, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
//        if (Username.getText().equals("Justin") && Password.getText().equals("admin123")) {
//            JOptionPane.showMessageDialog(null, "Login Successful!");
//        } else {
//            JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
//        }
        boolean loginSuccess = false;
        try{
            List<User> userList = UserPropertiesFileParsing.loadUsers(); // we have to use a try catch(
            
            for(User user: userList){
                if(user.getUserName().equals(Username.getText()) && user.getPassword().equals(Password.getText())){
                    System.out.println("Login Success!");
                    JOptionPane.showMessageDialog(null, "Login Successful!");
                    loginSuccess = true;
                    currentUser = Username.getText();
                    
                    if(user.getRole().equals("ADMIN")){
                        userIsAdmin = true;
                    }
                    break;
                }
            }
        } catch (IOException e) {}
        
        if(!loginSuccess){
            System.out.println("Invalid Username or Password!");
            JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
        }else{
            setVisible(false);
            new MainMenuUI().setVisible(true);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApplicationIcon;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField Password;
    private javax.swing.JLabel PasswordText;
    private javax.swing.JLabel TitleButton;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel UsernameText;
    // End of variables declaration//GEN-END:variables
}
