/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import dataAnalyze.ProductPropertiesFileParsing;
import java.awt.Desktop;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static main.AddProductInformation.ProductData;
import model.Product;

/**
 *
 * @author zhuangjinghao
 */
public class ProductSearch extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductSearch.class.getName());
    
    static {
        try {
            AddProductInformation.ProductData = (ArrayList<Product>) ProductPropertiesFileParsing.loadProducts();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
    /**
     * Creates new form ProductSearch
     */
    public ProductSearch() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        for(Product p : ProductData){
            model.addRow(new Object[]{p.getID(), p.getProductName(), p.getProductPrice(), p.getProductCategory(), p.getProductSupplier(), p.getStock()});
        }
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        SortButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        byName = new javax.swing.JButton();
        byID = new javax.swing.JButton();
        byCategory = new javax.swing.JButton();
        ReportLowStock = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        helpMenuBar = new javax.swing.JMenu();
        returnMenuBar = new javax.swing.JMenu();
        returnMainMenuBar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Resource Plan Beta 1.1");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Price ($)", "Category", "Supplier", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ProductTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 580));

        SortButton.setText("Sort Functon");
        SortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SortButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 120, -1));

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 120, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Search");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 50, 20));

        byName.setText("By Name");
        byName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byNameActionPerformed(evt);
            }
        });
        getContentPane().add(byName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 120, -1));

        byID.setText("By ID");
        byID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byIDActionPerformed(evt);
            }
        });
        getContentPane().add(byID, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 120, -1));

        byCategory.setText("By Category");
        byCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(byCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 120, -1));

        ReportLowStock.setText("Low Stock");
        ReportLowStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportLowStockActionPerformed(evt);
            }
        });
        getContentPane().add(ReportLowStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 120, -1));

        helpMenuBar.setText("Help");
        helpMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenuBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(helpMenuBar);

        returnMenuBar.setText("Return");

        returnMainMenuBar.setText("To Main Menu");
        returnMainMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMainMenuBarActionPerformed(evt);
            }
        });
        returnMenuBar.add(returnMainMenuBar);

        jMenuBar1.add(returnMenuBar);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void helpMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenuBarMouseClicked
        // TODO add your handling code here:
        // GPT's method to make the link clickable
        String url = "https://github.com/San1tater1122/ICS4U_Easy-Resources-Plan";

        JLabel link = new JLabel("<html>Go to our Github to see the tutorial! :)<br>"
            + "<a href=''>" + url + "</a></html>");

        link.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new java.net.URI(url));
                } catch (Exception ex) {}
            }
        });

        JOptionPane.showMessageDialog(null, link, "Tutorial", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_helpMenuBarMouseClicked

    private void returnMainMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMainMenuBarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MainMenuUI().setVisible(true);
    }//GEN-LAST:event_returnMainMenuBarActionPerformed
    
    private boolean idSortAscending = true;
    private void SortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortButtonActionPerformed
        // TODO add your handling code here:
        // 获取表格模型
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();

        // 创建或获取 TableRowSorter
        TableRowSorter<DefaultTableModel> sorter = (TableRowSorter<DefaultTableModel>) ProductTable.getRowSorter();
        if (sorter == null) {
            sorter = new TableRowSorter<>(model);
            ProductTable.setRowSorter(sorter);
        }

        // 设置排序键
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();

        if (idSortAscending) {
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING)); // ID 列升序
        } else {
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING)); // ID 列降序
        }
        sorter.setSortKeys(sortKeys);
        sorter.sort();

        // 切换排序状态，下次点击相反
        idSortAscending = !idSortAscending;
    }//GEN-LAST:event_SortButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void byNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byNameActionPerformed
        // TODO add your handling code here:
        // GPT's method
        TableRowSorter<DefaultTableModel> sorter;
        sorter = new TableRowSorter<>((DefaultTableModel) ProductTable.getModel());
        ProductTable.setRowSorter(sorter);
        
        String keyword = searchTextField.getText().trim();

        // 如果输入为空 → 显示全部
        if (keyword.isEmpty()) {
            sorter.setRowFilter(null);
            return;
        }

        // 自定义 RowFilter → 完全匹配 Name（列 1）
        sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
        @Override
            public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                String name = entry.getStringValue(1); // 列 1 = ProductName
                return name.equals(keyword);
            }
        });
    }//GEN-LAST:event_byNameActionPerformed

    private void byIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byIDActionPerformed
        // TODO add your handling code here:
        // learn by analogy
        TableRowSorter<DefaultTableModel> sorter;
        sorter = new TableRowSorter<>((DefaultTableModel) ProductTable.getModel());
        ProductTable.setRowSorter(sorter);
        
        String keyword = searchTextField.getText().trim();

        // 如果输入为空 → 显示全部
        if (keyword.isEmpty()) {
            sorter.setRowFilter(null);
            return;
        }

        // 自定义 RowFilter → 完全匹配 Name（列 1）
        sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
        @Override
            public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                String id = entry.getStringValue(0); // 列 1 = ProductName
                return id.equals(keyword);
            }
        });
    }//GEN-LAST:event_byIDActionPerformed

    private void byCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byCategoryActionPerformed
        // TODO add your handling code here:
        // still learn by analogy
        TableRowSorter<DefaultTableModel> sorter;
        sorter = new TableRowSorter<>((DefaultTableModel) ProductTable.getModel());
        ProductTable.setRowSorter(sorter);
        
        String keyword = searchTextField.getText().trim();

        // 如果输入为空 → 显示全部
        if (keyword.isEmpty()) {
            sorter.setRowFilter(null);
            return;
        }

        // 自定义 RowFilter → 完全匹配 Name（列 1）
        sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
        @Override
            public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                String category = entry.getStringValue(3); // 列 1 = ProductName
                return category.equals(keyword);
            }
        });
    }//GEN-LAST:event_byCategoryActionPerformed
    
    boolean ReportLowStockVal = true;
    private void ReportLowStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportLowStockActionPerformed
        // TODO add your handling code here:
        // still learn by analogy
        TableRowSorter<DefaultTableModel> sorter;
        sorter = new TableRowSorter<>((DefaultTableModel) ProductTable.getModel());
        ProductTable.setRowSorter(sorter);
        
        if(ReportLowStockVal){
            sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
            @Override
                public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                    String stockStr = entry.getStringValue(5); // 第 5 列 = stock
                    try {
                        int stock = Integer.parseInt(stockStr);
                        ReportLowStockVal = false;
                        return stock <= 50;   // 显示库存小于 50 的
                    } catch (NumberFormatException e) {
                        return false; // 非数字就不显示
                    }
                }
            });
        }else{
            sorter.setRowFilter(null);
            ReportLowStockVal = true;
            return;
        }
    }//GEN-LAST:event_ReportLowStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductSearch().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton ReportLowStock;
    private javax.swing.JButton SortButton;
    private javax.swing.JButton byCategory;
    private javax.swing.JButton byID;
    private javax.swing.JButton byName;
    private javax.swing.JMenu helpMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem returnMainMenuBar;
    private javax.swing.JMenu returnMenuBar;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
