/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import dataAnalyze.ProductPropertiesFileParsing;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Product;
import dataAnalyze.RebuildProductProperties;
import java.awt.Desktop;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

import main.AddProductInformation;

/**
 *
 * @author zhuangjinghao
 */
public class RemoveAndModifyProductInformation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RemoveAndModifyProductInformation.class.getName());
   
    static {
        try {
            AddProductInformation.ProductData = (ArrayList<Product>) ProductPropertiesFileParsing.loadProducts();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
    /**
     * Creates new form removeProductInformation
     */
    public RemoveAndModifyProductInformation() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        for(Product p : AddProductInformation.ProductData){
            model.addRow(new Object[]{p.getID(), p.getProductName(), p.getProductPrice(), p.getProductCategory(), p.getProductSupplier(), p.getStock()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        RemoveButton = new javax.swing.JButton();
        SortButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        helpMenuBar = new javax.swing.JMenu();
        returnMenuBar = new javax.swing.JMenu();
        returnMainMenuBar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Resource Plan Beta 1.1");
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Price ($)", "Category", "Supplier", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ProductTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 580));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select And Remove");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 120, -1));

        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 120, -1));

        SortButton.setText("Sort Functon");
        SortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SortButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 120, -1));

        SaveButton.setText("Save Changes");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 120, 30));

        helpMenuBar.setText("Help");
        helpMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMenuBarMouseClicked(evt);
            }
        });
        jMenuBar1.add(helpMenuBar);

        returnMenuBar.setText("Return");

        returnMainMenuBar.setText("To Main Menu");
        returnMainMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMainMenuBarActionPerformed(evt);
            }
        });
        returnMenuBar.add(returnMainMenuBar);

        jMenuBar1.add(returnMenuBar);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnMainMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMainMenuBarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MainMenuUI().setVisible(true);
    }//GEN-LAST:event_returnMainMenuBarActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        
        // This section uses ChatGPT because it's used to determine how to delete items from a list.
        // 1️⃣ 获取选中的行
        int selectedRow = ProductTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product to delete!");
            return;
        }

        // 2️⃣ 获取选中的产品 ID
        String targetId = ProductTable.getValueAt(selectedRow, 0).toString();

        // 3️⃣ 删除内存列表中的 product
        AddProductInformation.ProductData.removeIf(p -> p.getID() == Integer.parseInt(targetId));

        // 4️⃣ 删除 properties 文件中的 product
        Properties prop = new Properties();
        try (FileInputStream in = new FileInputStream("data/products.properties")) {
            prop.load(in);
        } catch (IOException e) {
        }

        // 遍历找到对应 index 并删除对应 key
        int index = 0;
        while (prop.containsKey("product" + index + ".id")) {
            if (prop.getProperty("product" + index + ".id").equals(targetId)) {
                prop.remove("product" + index + ".id");
                prop.remove("product" + index + ".ProductName");
                prop.remove("product" + index + ".ProductPrice");
                prop.remove("product" + index + ".ProductCategory");
                prop.remove("product" + index + ".ProductSupplier");
                prop.remove("product" + index + ".stock");
                break;
            }
            index++;
        }

        // 保存回文件
        try {
            FileOutputStream out = new FileOutputStream("data/products.properties");
            prop.store(out, "Rebuilt Product Data by: " + LoginUI.currentUser);
        } catch (IOException ex) {
            System.getLogger(RemoveAndModifyProductInformation.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        // 5️⃣ 从 JTable 删除对应行
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        model.removeRow(selectedRow);

        JOptionPane.showMessageDialog(this, "Product deleted successfully!");
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            try {
                int id = Integer.parseInt(model.getValueAt(i, 0).toString());
                String name = model.getValueAt(i, 1).toString();
                float price = Float.parseFloat(model.getValueAt(i, 2).toString());
                String category = model.getValueAt(i, 3).toString();
                String supplier = model.getValueAt(i, 4).toString();
                int stock = Integer.parseInt(model.getValueAt(i, 5).toString());

                // 在 ProductData 中找对应的 product
                for (Product p : AddProductInformation.ProductData) {
                    if (p.getID() == id) { // 注意：Product.java 里是 getID()
                        p.resetProductName(name);
                        p.resetProductPrice(price);
                        p.resetProductCategory(category);
                        p.resetProductSupplier(supplier);
                        p.resetStock(stock);
                        break;
                    }
                }
            } catch (Exception e) {}
        }
        
        RebuildProductProperties.rebuildProductProperties(AddProductInformation.ProductData);
        
    }//GEN-LAST:event_SaveButtonActionPerformed
    
    private boolean idSortAscending = true;
    private void SortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortButtonActionPerformed
        // TODO add your handling code here:
        // 获取表格模型
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();

        // 创建或获取 TableRowSorter
        TableRowSorter<DefaultTableModel> sorter = (TableRowSorter<DefaultTableModel>) ProductTable.getRowSorter();
        if (sorter == null) {
            sorter = new TableRowSorter<>(model);
            ProductTable.setRowSorter(sorter);
        }

        // 设置排序键
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        if (idSortAscending) {
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING)); // ID 列升序
        } else {
            sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING)); // ID 列降序
        }
        sorter.setSortKeys(sortKeys);
        sorter.sort();

        // 切换排序状态，下次点击相反
        idSortAscending = !idSortAscending;
    }//GEN-LAST:event_SortButtonActionPerformed

    private void helpMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMenuBarMouseClicked
        // TODO add your handling code here:
        // GPT's method to make the link clickable
        String url = "https://github.com/San1tater1122/ICS4U_Easy-Resources-Plan";

        JLabel link = new JLabel("<html>Go to our Github to see the tutorial! :)<br>"
                + "<a href=''>" + url + "</a></html>");

        link.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new java.net.URI(url));
                } catch (Exception ex) {}
            }
        });

        JOptionPane.showMessageDialog(null, link, "Tutorial", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_helpMenuBarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RemoveAndModifyProductInformation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SortButton;
    private javax.swing.JMenu helpMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem returnMainMenuBar;
    private javax.swing.JMenu returnMenuBar;
    // End of variables declaration//GEN-END:variables
}
